In [1]:
import sys, os

src = os.path.abspath(os.path.join(os.getcwd(), os.pardir))
sys.path.append(src)

from src.pipeline_late_fusion import *
from src.pipeline_early_fusion import *
from src.pipeline_audio_model import *
from src.pipeline_text_model import *
import json

c:\Users\victo\Documents\GitHub\PROJET_SAM\notebooks


C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)


c:\Users\victo\Documents\GitHub\PROJET_SAM\notebooks


C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


c:\Users\victo\Documents\GitHub\PROJET_SAM\notebooks
c:\Users\victo\Documents\GitHub\PROJET_SAM\notebooks


# Déclaration des seeds

In [3]:
seeds=range(10)

# Texte 

In [6]:

model_name='exp'
patience=3
num_epochs=1
model_name='test'
class_weight=[1.0,3.6]
task="turn_after"

f1_score_train_text=[]
f1_score_test_text=[]
conf_matrix_train_text=[]
conf_matrix_test_text=[]
kappa_test_text=[]
kappa_train_text=[]
for seed in seeds:
    if os.path.exists(f"../experiences/texte/SEED_{seed}")==False:
        os.mkdir(f"../experiences/texte/SEED_{seed}")
        
    f1_train,conf_train,kappa_train,f1_test,conf_test,kappa_test=training_eval_model_text(num_epochs,seed,model_name,patience,class_weight,task,save=False)
    f1_score_train_text.append(f1_train)
    f1_score_test_text.append(f1_test)
    conf_matrix_train_text.append(conf_train)
    conf_matrix_test_text.append(conf_test)
    kappa_test_text.append(kappa_test)
    kappa_train_text.append(kappa_train)
    
    #stockage des résultats
        #stockage des résultats
    results = {
    "f1_score_train": f1_train,
    "f1_score_test": f1_test,
    "conf_matrix_train": conf_train.tolist() if isinstance(conf_train, np.ndarray) else conf_train,
    "conf_matrix_test": conf_test.tolist() if isinstance(conf_test, np.ndarray) else conf_test,
    "kappa_test": kappa_test,
    "kappa_train": kappa_train
}
 
    with open(f"../experiences/texte/SEED_{seed}/results.json", 'w') as outfile:
        json.dump(results, outfile)
    

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


Utilisation de l'appareil: cuda


Some weights of CamembertForSequenceClassification were not initialized from the model checkpoint at camembert-base and are newly initialized: ['classifier.out_proj.weight', 'classifier.out_proj.bias', 'classifier.dense.weight', 'classifier.dense.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\transformers\optimization.py:429: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


Epoch 0
validation  f1 score : 0.0
Score F1 de test: 0.21867440735365262
Matrice de confusion:
[[9424 1257]
 [1973  452]]
Nombre d'éléments de classe 0 détectés : 9424 sur 10681
Nombre d'éléments de classe 1 détectés : 452 sur 2425
Score F1 de test: 0.22986247544204322
Matrice de confusion:
[[2379  299]
 [ 485  117]]
Nombre d'éléments de classe 0 détectés : 2379 sur 2678
Nombre d'éléments de classe 1 détectés : 117 sur 602


Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


Utilisation de l'appareil: cuda


Some weights of CamembertForSequenceClassification were not initialized from the model checkpoint at camembert-base and are newly initialized: ['classifier.out_proj.weight', 'classifier.out_proj.bias', 'classifier.dense.weight', 'classifier.dense.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\transformers\optimization.py:429: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


Epoch 0
validation  f1 score : 0.0
Score F1 de test: 0.3525309917355372
Matrice de confusion:
[[6727 3991]
 [1023 1365]]
Nombre d'éléments de classe 0 détectés : 6727 sur 10718
Nombre d'éléments de classe 1 détectés : 1365 sur 2388
Score F1 de test: 0.3629032258064516
Matrice de confusion:
[[1656  985]
 [ 279  360]]
Nombre d'éléments de classe 0 détectés : 1656 sur 2641
Nombre d'éléments de classe 1 détectés : 360 sur 639


Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


Utilisation de l'appareil: cuda


Some weights of CamembertForSequenceClassification were not initialized from the model checkpoint at camembert-base and are newly initialized: ['classifier.out_proj.weight', 'classifier.out_proj.bias', 'classifier.dense.weight', 'classifier.dense.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\transformers\optimization.py:429: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


Epoch 0
validation  f1 score : 0.4
Score F1 de test: 0.2520152736529486
Matrice de confusion:
[[8986 1682]
 [1844  594]]
Nombre d'éléments de classe 0 détectés : 8986 sur 10668
Nombre d'éléments de classe 1 détectés : 594 sur 2438
Score F1 de test: 0.2591687041564792
Matrice de confusion:
[[2212  477]
 [ 432  159]]
Nombre d'éléments de classe 0 détectés : 2212 sur 2689
Nombre d'éléments de classe 1 détectés : 159 sur 591


Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


Utilisation de l'appareil: cuda


Some weights of CamembertForSequenceClassification were not initialized from the model checkpoint at camembert-base and are newly initialized: ['classifier.out_proj.weight', 'classifier.out_proj.bias', 'classifier.dense.weight', 'classifier.dense.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\transformers\optimization.py:429: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


Epoch 0
validation  f1 score : 0.0
Score F1 de test: 0.3490806945863126
Matrice de confusion:
[[6641 4067]
 [1031 1367]]
Nombre d'éléments de classe 0 détectés : 6641 sur 10708
Nombre d'éléments de classe 1 détectés : 1367 sur 2398
Score F1 de test: 0.3722334004024144
Matrice de confusion:
[[1662  988]
 [ 260  370]]
Nombre d'éléments de classe 0 détectés : 1662 sur 2650
Nombre d'éléments de classe 1 détectés : 370 sur 630


Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


Utilisation de l'appareil: cuda


Some weights of CamembertForSequenceClassification were not initialized from the model checkpoint at camembert-base and are newly initialized: ['classifier.out_proj.weight', 'classifier.out_proj.bias', 'classifier.dense.weight', 'classifier.dense.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\transformers\optimization.py:429: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


Epoch 0
validation  f1 score : 0.36363636363636365
Score F1 de test: 0.3740161844584857
Matrice de confusion:
[[5772 4901]
 [ 746 1687]]
Nombre d'éléments de classe 0 détectés : 5772 sur 10673
Nombre d'éléments de classe 1 détectés : 1687 sur 2433
Score F1 de test: 0.3566651805617477
Matrice de confusion:
[[1437 1250]
 [ 193  400]]
Nombre d'éléments de classe 0 détectés : 1437 sur 2687
Nombre d'éléments de classe 1 détectés : 400 sur 593


Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


Utilisation de l'appareil: cuda


Some weights of CamembertForSequenceClassification were not initialized from the model checkpoint at camembert-base and are newly initialized: ['classifier.out_proj.weight', 'classifier.out_proj.bias', 'classifier.dense.weight', 'classifier.dense.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\transformers\optimization.py:429: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


Epoch 0
validation  f1 score : 0.5454545454545454
Score F1 de test: 0.37298387096774194
Matrice de confusion:
[[5843 4840]
 [ 758 1665]]
Nombre d'éléments de classe 0 détectés : 5843 sur 10683
Nombre d'éléments de classe 1 détectés : 1665 sur 2423
Score F1 de test: 0.36917562724014336
Matrice de confusion:
[[1460 1217]
 [ 191  412]]
Nombre d'éléments de classe 0 détectés : 1460 sur 2677
Nombre d'éléments de classe 1 détectés : 412 sur 603


Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


Utilisation de l'appareil: cuda


Some weights of CamembertForSequenceClassification were not initialized from the model checkpoint at camembert-base and are newly initialized: ['classifier.out_proj.weight', 'classifier.out_proj.bias', 'classifier.dense.weight', 'classifier.dense.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\transformers\optimization.py:429: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


Epoch 0
validation  f1 score : 0.16666666666666669
Score F1 de test: 0.3544737744257799
Matrice de confusion:
[[5906 4819]
 [ 830 1551]]
Nombre d'éléments de classe 0 détectés : 5906 sur 10725
Nombre d'éléments de classe 1 détectés : 1551 sur 2381
Score F1 de test: 0.3722595078299776
Matrice de confusion:
[[1461 1171]
 [ 232  416]]
Nombre d'éléments de classe 0 détectés : 1461 sur 2632
Nombre d'éléments de classe 1 détectés : 416 sur 648


Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


Utilisation de l'appareil: cuda


Some weights of CamembertForSequenceClassification were not initialized from the model checkpoint at camembert-base and are newly initialized: ['classifier.out_proj.weight', 'classifier.out_proj.bias', 'classifier.dense.weight', 'classifier.dense.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\transformers\optimization.py:429: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


Epoch 0
validation  f1 score : 0.0
Score F1 de test: 0.0616061606160616
Matrice de confusion:
[[10463   215]
 [ 2344    84]]
Nombre d'éléments de classe 0 détectés : 10463 sur 10678
Nombre d'éléments de classe 1 détectés : 84 sur 2428
Score F1 de test: 0.06725146198830409
Matrice de confusion:
[[2619   62]
 [ 576   23]]
Nombre d'éléments de classe 0 détectés : 2619 sur 2681
Nombre d'éléments de classe 1 détectés : 23 sur 599


Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


Utilisation de l'appareil: cuda


Some weights of CamembertForSequenceClassification were not initialized from the model checkpoint at camembert-base and are newly initialized: ['classifier.out_proj.weight', 'classifier.out_proj.bias', 'classifier.dense.weight', 'classifier.dense.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\transformers\optimization.py:429: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


Epoch 0
validation  f1 score : 0.4
Score F1 de test: 0.32086773514651123
Matrice de confusion:
[[7920 2740]
 [1455  991]]
Nombre d'éléments de classe 0 détectés : 7920 sur 10660
Nombre d'éléments de classe 1 détectés : 991 sur 2446
Score F1 de test: 0.2860980523841504
Matrice de confusion:
[[2004  695]
 [ 368  213]]
Nombre d'éléments de classe 0 détectés : 2004 sur 2699
Nombre d'éléments de classe 1 détectés : 213 sur 581


Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


Utilisation de l'appareil: cuda


Some weights of CamembertForSequenceClassification were not initialized from the model checkpoint at camembert-base and are newly initialized: ['classifier.out_proj.weight', 'classifier.out_proj.bias', 'classifier.dense.weight', 'classifier.dense.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\transformers\optimization.py:429: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


Epoch 0
validation  f1 score : 0.22222222222222224
Score F1 de test: 0.36667861838173776
Matrice de confusion:
[[6273 4399]
 [ 900 1534]]
Nombre d'éléments de classe 0 détectés : 6273 sur 10672
Nombre d'éléments de classe 1 détectés : 1534 sur 2434
Score F1 de test: 0.35838150289017345
Matrice de confusion:
[[1576 1110]
 [ 222  372]]
Nombre d'éléments de classe 0 détectés : 1576 sur 2686
Nombre d'éléments de classe 1 détectés : 372 sur 594


# Audio

In [4]:
num_epochs=5
model_name='test'
patience=20
class_weight=[1.0,4.0] # attention float
task="turn_after"
save=True
f1_score_train_audio=[]
f1_score_test_audio=[]
conf_matrix_train_audio=[]
conf_matrix_test_audio=[]
kappa_test_audio=[]
kappa_train_audio=[]
for seed in seeds:
    
    if os.path.exists(f"../experiences/audio/SEED_{seed}")==False:
        os.mkdir(f"../experiences/audio/SEED_{seed}")
        
    f1_train,conf_train,kappa_train,f1_test,conf_test,kappa_test=training_eval_model_audio(num_epochs,seed,model_name,patience,class_weight,task,save=True)
    f1_score_train_audio.append(f1_train)
    f1_score_test_audio.append(f1_test)
    conf_matrix_train_audio.append(conf_train)
    conf_matrix_test_audio.append(conf_test)
    kappa_test_audio.append(kappa_test)
    kappa_train_audio.append(kappa_train)
    
    #stockage des résultats
    results = {
    "f1_score_train": f1_train,
    "f1_score_test": f1_test,
    "conf_matrix_train": conf_train.tolist() if isinstance(conf_train, np.ndarray) else conf_train,
    "conf_matrix_test": conf_test.tolist() if isinstance(conf_test, np.ndarray) else conf_test,
    "kappa_test": kappa_test,
    "kappa_train": kappa_train
}
    
    with open(f"../experiences/audio/SEED_{seed}/results.json", 'w') as fp:
        json.dump(results, fp)
    

tache turn_after


C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\librosa\core\spectrum.py:257: UserWarning: n_fft=2048 is too large for input signal of length=1920
  warnings.warn(
C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\librosa\core\spectrum.py:257: UserWarning: n_fft=2048 is too large for input signal of length=1280
  warnings.warn(
C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\librosa\core\spectrum.py:257: UserWarning: n_fft=2048 is too large for input signal of length=1120
  warnings.warn(
C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\librosa\core\spectrum.py:257: UserWarning: n_fft=2048 is too large for input signal of length=18

Using device: cuda
20
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
tor

C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\librosa\core\spectrum.py:257: UserWarning: n_fft=2048 is too large for input signal of length=1920
  warnings.warn(
C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\librosa\core\spectrum.py:257: UserWarning: n_fft=2048 is too large for input signal of length=1280
  warnings.warn(
C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\librosa\core\spectrum.py:257: UserWarning: n_fft=2048 is too large for input signal of length=1120
  warnings.warn(
C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\librosa\core\spectrum.py:257: UserWarning: n_fft=2048 is too large for input signal of length=18

Using device: cuda
20
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
tor

C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\librosa\core\spectrum.py:257: UserWarning: n_fft=2048 is too large for input signal of length=1920
  warnings.warn(
C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\librosa\core\spectrum.py:257: UserWarning: n_fft=2048 is too large for input signal of length=1280
  warnings.warn(
C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\librosa\core\spectrum.py:257: UserWarning: n_fft=2048 is too large for input signal of length=1120
  warnings.warn(
C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\librosa\core\spectrum.py:257: UserWarning: n_fft=2048 is too large for input signal of length=18

Using device: cuda
20
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
tor

C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\librosa\core\spectrum.py:257: UserWarning: n_fft=2048 is too large for input signal of length=1920
  warnings.warn(
C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\librosa\core\spectrum.py:257: UserWarning: n_fft=2048 is too large for input signal of length=1280
  warnings.warn(
C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\librosa\core\spectrum.py:257: UserWarning: n_fft=2048 is too large for input signal of length=1120
  warnings.warn(
C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\librosa\core\spectrum.py:257: UserWarning: n_fft=2048 is too large for input signal of length=18

Using device: cuda
20
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
tor

C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\librosa\core\spectrum.py:257: UserWarning: n_fft=2048 is too large for input signal of length=1920
  warnings.warn(
C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\librosa\core\spectrum.py:257: UserWarning: n_fft=2048 is too large for input signal of length=1280
  warnings.warn(
C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\librosa\core\spectrum.py:257: UserWarning: n_fft=2048 is too large for input signal of length=1120
  warnings.warn(
C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\librosa\core\spectrum.py:257: UserWarning: n_fft=2048 is too large for input signal of length=18

Using device: cuda
20
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
tor

C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\librosa\core\spectrum.py:257: UserWarning: n_fft=2048 is too large for input signal of length=1920
  warnings.warn(
C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\librosa\core\spectrum.py:257: UserWarning: n_fft=2048 is too large for input signal of length=1280
  warnings.warn(
C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\librosa\core\spectrum.py:257: UserWarning: n_fft=2048 is too large for input signal of length=1120
  warnings.warn(
C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\librosa\core\spectrum.py:257: UserWarning: n_fft=2048 is too large for input signal of length=18

Using device: cuda
20
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
tor

C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\librosa\core\spectrum.py:257: UserWarning: n_fft=2048 is too large for input signal of length=1920
  warnings.warn(
C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\librosa\core\spectrum.py:257: UserWarning: n_fft=2048 is too large for input signal of length=1280
  warnings.warn(
C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\librosa\core\spectrum.py:257: UserWarning: n_fft=2048 is too large for input signal of length=1120
  warnings.warn(
C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\librosa\core\spectrum.py:257: UserWarning: n_fft=2048 is too large for input signal of length=18

Using device: cuda
20
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
tor

C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\librosa\core\spectrum.py:257: UserWarning: n_fft=2048 is too large for input signal of length=1920
  warnings.warn(
C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\librosa\core\spectrum.py:257: UserWarning: n_fft=2048 is too large for input signal of length=1280
  warnings.warn(
C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\librosa\core\spectrum.py:257: UserWarning: n_fft=2048 is too large for input signal of length=1120
  warnings.warn(
C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\librosa\core\spectrum.py:257: UserWarning: n_fft=2048 is too large for input signal of length=18

Using device: cuda
20
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
tor

C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\librosa\core\spectrum.py:257: UserWarning: n_fft=2048 is too large for input signal of length=1920
  warnings.warn(
C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\librosa\core\spectrum.py:257: UserWarning: n_fft=2048 is too large for input signal of length=1280
  warnings.warn(
C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\librosa\core\spectrum.py:257: UserWarning: n_fft=2048 is too large for input signal of length=1120
  warnings.warn(
C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\librosa\core\spectrum.py:257: UserWarning: n_fft=2048 is too large for input signal of length=18

Using device: cuda
20
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
tor

C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\librosa\core\spectrum.py:257: UserWarning: n_fft=2048 is too large for input signal of length=1920
  warnings.warn(
C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\librosa\core\spectrum.py:257: UserWarning: n_fft=2048 is too large for input signal of length=1280
  warnings.warn(
C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\librosa\core\spectrum.py:257: UserWarning: n_fft=2048 is too large for input signal of length=1120
  warnings.warn(
C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\librosa\core\spectrum.py:257: UserWarning: n_fft=2048 is too large for input signal of length=18

Using device: cuda
20
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
torch.Size([16, 1, 128])
tor

# Early 

In [7]:
patience=3
save=False
model_name="exp"

num_epochs=3
patience=1
class_weight=[1.0,5.1]
task="turn_after"
save=True
f1_score_train_early=[]
f1_score_test_early=[]
conf_matrix_train_early=[]
conf_matrix_test_early=[]
kappa_test_early=[]
kappa_train_early=[]
for seed in seeds:
    if os.path.exists(f"../experiences/early/SEED_{seed}")==False:
        os.mkdir(f"../experiences/early/SEED_{seed}")
    f1_train,conf_train,kappa_train,f1_test,conf_test,kappa_test=training_evaluate_model_audio_text_early(num_epochs,seed,model_name,patience,class_weight,task,save=True)
    f1_score_train_early.append(f1_train)
    f1_score_test_early.append(f1_test)
    conf_matrix_train_early.append(conf_train)
    conf_matrix_test_early.append(conf_test)
    kappa_test_early.append(kappa_test)
    kappa_train_early.append(kappa_train)
    
    #stockage des résultats
    results = {
    "f1_score_train": f1_train,
    "f1_score_test": f1_test,
    "conf_matrix_train": conf_train.tolist() if isinstance(conf_train, np.ndarray) else conf_train,
    "conf_matrix_test": conf_test.tolist() if isinstance(conf_test, np.ndarray) else conf_test,
    "kappa_test": kappa_test,
    "kappa_train": kappa_train
}
    with open(f"../experiences/early/SEED_{seed}/results.json", 'w') as fp:
        json.dump(results, fp)
    

C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\librosa\core\spectrum.py:257: UserWarning: n_fft=2048 is too large for input signal of length=1920
  warnings.warn(
C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\librosa\core\spectrum.py:257: UserWarning: n_fft=2048 is too large for input signal of length=1280
  warnings.warn(
C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\librosa\core\spectrum.py:257: UserWarning: n_fft=2048 is too large for input signal of length=1120
  warnings.warn(
C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\librosa\core\spectrum.py:257: UserWarning: n_fft=2048 is too large for input signal of length=18

Utilisation de l'appareil: cuda
1
Batch 1/812
Batch 2/812
Batch 3/812
Batch 4/812
Batch 5/812
Batch 6/812
Batch 7/812
Batch 8/812
Batch 9/812
Batch 10/812
Batch 11/812
Batch 12/812
Batch 13/812
Batch 14/812
Batch 15/812
Batch 16/812
Batch 17/812
Batch 18/812
Batch 19/812
Batch 20/812
Batch 21/812
Batch 22/812
Batch 23/812
Batch 24/812
Batch 25/812
Batch 26/812
Batch 27/812
Batch 28/812
Batch 29/812
Batch 30/812
Batch 31/812
Batch 32/812
Batch 33/812
Batch 34/812
Batch 35/812
Batch 36/812
Batch 37/812
Batch 38/812
Batch 39/812
Batch 40/812
Batch 41/812
Batch 42/812
Batch 43/812
Batch 44/812
Batch 45/812
Batch 46/812
Batch 47/812
Batch 48/812
Batch 49/812
Batch 50/812
Batch 51/812
Batch 52/812
Batch 53/812
Batch 54/812
Batch 55/812
Batch 56/812
Batch 57/812
Batch 58/812
Batch 59/812
Batch 60/812
Batch 61/812
Batch 62/812
Batch 63/812
Batch 64/812
Batch 65/812
Batch 66/812
Batch 67/812
Batch 68/812
Batch 69/812
Batch 70/812
Batch 71/812
Batch 72/812
Batch 73/812
Batch 74/812
Batch 75/812


TypeError: Object of type ndarray is not JSON serializable

# Late


In [ ]:
patience=3
class_weight=[1.0,3.0]
task="turn_after"
save=False
model_name="exp"
num_epochs=1
save=False
all_training=False
f1_score_train_late=[]
f1_score_test_late=[]
conf_matrix_train_late=[]
conf_matrix_test_late=[]
kappa_test_late=[]
kappa_train_late=[]
for seed in seeds:
    if os.path.exists(f"../experiences/late/SEED_{seed}")==False:
        os.mkdir(f"../experiences/late/SEED_{seed}")
    f1_train,conf_train,kappa_train,f1_test,conf_test,kappa_test=training_evaluate_model_audio_text_late(num_epochs,seed,model_name,patience,class_weight,task,save,all_training)
    f1_score_train_late.append(f1_train)
    f1_score_test_late.append(f1_test)
    conf_matrix_train_late.append(conf_train)
    conf_matrix_test_late.append(conf_test)
    kappa_test_late.append(kappa_test)
    kappa_train_late.append(kappa_train)
    
    #stockage des résultats
    results={"f1_score_train":f1_train,"f1_score_test":f1_test,"conf_matrix_train":conf_train,"conf_matrix_test":conf_test,"kappa_test":kappa_test,"kappa_train":kappa_train}
    with open(f"../experiences/late/SEED_{seed}/results.json", 'w') as fp:
        json.dump(results, fp)
    