# Import

In [1]:
import sys, os

src = os.path.abspath(os.path.join(os.getcwd(), os.pardir))
sys.path.append(src)

from src.pipeline_text_model import *

C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


# All pipeline in one function calling : 

In [2]:
training_eval_model_text(num_epochs=1,seed=1,model_name='test',patience=3,class_weight=[1.0,3.6],task="turn_after",save=True)

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


Utilisation de l'appareil: cuda


Some weights of CamembertForSequenceClassification were not initialized from the model checkpoint at camembert-base and are newly initialized: ['classifier.dense.bias', 'classifier.out_proj.bias', 'classifier.dense.weight', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\transformers\optimization.py:429: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


Epoch 0
validation  f1 score : 0.2222222222222222
Score F1 de test: 0.359117361784675
Matrice de confusion:
[[6339 4379]
 [ 907 1481]]
Nombre d'éléments de classe 0 détectés : 6339 sur 10718
Nombre d'éléments de classe 1 détectés : 1481 sur 2388
Score F1 de test: 0.36921624173748824
Matrice de confusion:
[[1553 1088]
 [ 248  391]]
Nombre d'éléments de classe 0 détectés : 1553 sur 2641
Nombre d'éléments de classe 1 détectés : 391 sur 639


(0.359117361784675,
 array([[6339, 4379],
        [ 907, 1481]], dtype=int64),
 0.13522015373483132,
 0.36921624173748824,
 array([[1553, 1088],
        [ 248,  391]], dtype=int64),
 0.13344162149057193)

# Pipeline in 3 functions calling : 

# 1 Loading data

In [ ]:
train_loader,val_loader,test_loader=load_data_text(seed=1,task="turn_after")


Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


# 2 Training data

In [ ]:
num_epochs=1
seed=1
model_name="test"
patience=1
class_weight=[1.0,3.5] # attention float
task="turn_after"
save=False
model=training_model_text(num_epochs,seed,model_name,train_loader,val_loader,patience,class_weight=class_weight,task=task,save=save)
    

Utilisation de l'appareil: cuda


Some weights of CamembertForSequenceClassification were not initialized from the model checkpoint at camembert-base and are newly initialized: ['classifier.out_proj.weight', 'classifier.out_proj.bias', 'classifier.dense.weight', 'classifier.dense.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
C:\Users\victo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\transformers\optimization.py:429: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


Epoch 0
Early stopping


# 3  Evaluate data

In [ ]:
evaluate_model_text(model,model_name,task,test_loader,model_save=False)

Score F1 de test: 0.003110419906687403
Matrice de confusion:
[[2638    3]
 [ 638    1]]
Nombre d'éléments de classe 0 détectés : 2638 sur 2641
Nombre d'éléments de classe 1 détectés : 1 sur 639


(0.003110419906687403,
 array([[2638,    3],
        [ 638,    1]], dtype=int64),
 0.0006882364795753881)